# fly.toml app configuration file generated for learntocodefyi on 2024-01-02T20:33:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "learntocodefyi"
primary_region = "sjc"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[env]
PLATFORM = "PROD"
