// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: responses.sql

package sqlcdb

import (
	"context"
)

const createResponse = `-- name: CreateResponse :one
INSERT INTO responses (
    id,
    user_id,
    question_id,
    survey_id,
    answer,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    DATE('now')
) RETURNING id, user_id, question_id, survey_id, answer, created_at
`

type CreateResponseParams struct {
	ID         string
	UserID     string
	QuestionID string
	SurveyID   string
	Answer     string
}

func (q *Queries) CreateResponse(ctx context.Context, arg CreateResponseParams) (Response, error) {
	row := q.db.QueryRowContext(ctx, createResponse,
		arg.ID,
		arg.UserID,
		arg.QuestionID,
		arg.SurveyID,
		arg.Answer,
	)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.SurveyID,
		&i.Answer,
		&i.CreatedAt,
	)
	return i, err
}
