// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: users.sql

package sqlcdb

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    hashed_ip,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    DATE('now'),
    DATE('now')
) RETURNING id, hashed_ip, created_at, updated_at
`

type CreateUserParams struct {
	ID       string
	HashedIp string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.HashedIp)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
